[package]
name = "rls-data"
version = "0.1.0"
authors = ["Nick Cameron <ncameron@mozilla.com>"]

[dependencies]
rls-span = { git = "https://github.com/nrc/rls-span", features = ["serialize-rustc"] }
rustc-serialize = "0.3"
