[package]
name = "rls-data"
version = "0.1.0"
authors = ["Nick Cameron <ncameron@mozilla.com>"]

[dependencies]
rls-span = { git = "https://github.com/nrc/rls-span" }
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
